name: astribot_making_coffee_image

shape_meta: &shape_meta
  obs:
    cam_head:
      shape: [3, 240, 320]
      type: rgb
    cam_left_wrist:
      shape: [3, 240, 320]
      type: rgb
    cam_right_wrist:
      shape: [3, 240, 320]
      type: rgb
    state:
      shape: [16]
      type: low_dim
  action: 
    shape: [16]

task_name: &task_name astribot_making_coffee
dataset_path: &dataset_path /home/anhnb9/Documents/datasets/astri_making_coffee_v21.zarr

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.astribot_image_dataset.AstribotImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  seed: 42
  val_ratio: 0.05
  max_train_episodes: null
  use_cache: True
  max_cache_size_gb: 50.0
  background_preload: True
  preload_delay_sec: 1.0
  preload_sleep_sec: 0.01
